# specify the node base image with your desired version node:<version>
#FROM node:10
FROM node

# replace this with your application's default port
EXPOSE 3000

ENV NPM_CONFIG_LOGLEVEL info

WORKDIR app

COPY package*.json ./
RUN npm install

COPY . .

CMD ["node", "app.js"]